class NotFoundError(BaseException):
    pass


class AlreadyExistsError(BaseException):
    pass
