class NotFoundError(BaseException):
    pass


class AlreadyExists(BaseException):
    pass
